### ISSUE TITLE
Request for more details

### ISSUE THREAD

**Issue by zwyy5520** [mrmckain/PhyDS#1]
Hi，
   This software PhyDS is useful for my work but the description is too simple , so I am confused about the input and output of it , I hope to get a detailed example, thank you very much!

**Comment by mrmckain** [comment]
Hello,

Yes. I will be provide much more detail very soon. My apologies that it is not up already.

Happy New Year!
Michael

**Comment by chenxq815** [comment]
Hi, 
I saw PhyDS in the strawberry genome article, I would love to use this software, but this tutorial is really too simple. I hope to have a detailed description as soon as possible. Thank you very much.

**Comment by mrmckain** [comment]
More detail has been added. More will come in the next day or so to explain output files.
