### ISSUE TITLE
Use of uninitialized value $target_id

### ISSUE THREAD

**Issue by goeckeritz** [mrmckain/PhyDS#2]
Hi Michael, 

Thanks so much for making this super useful tool! I'm trying to use it to find the sister ortholog of a set of genes in a tree, but I keep hitting a wall. I'm using a shared HPC system and have loaded our BioPerl module and checked that the perl module dependencies were installed (Getopt::Long and Bio but not Bio:TreeIO explicitly).

I think this is okay though because a recognition of the dependencies doesn't seem to be the problem. I try the following command (note that --ignore is just a ',' because I'm just testing to see if it will run initially and don't care if it reports the sister of every gene):

**perl phyds.2.pl -p /1_to_1_gene_lists/OG0018625_gene_list.txt --ignore , --trees filter_1_to_1_orthologs/bestTrees/ --name OG0018625 --bootstrap 90**

And I get the following report, along with empty files:
Use of uninitialized value $target_id in regexp compilation at phyds.2.pl line 215, <GEN31> line 1.
Use of uninitialized value $target_id in regexp compilation at phyds.2.pl line 216, <GEN31> line 1.
Use of uninitialized value $target_id in regexp compilation at phyds.2.pl line 215, <GEN31> line 1.
Use of uninitialized value $target_id in regexp compilation at phyds.2.pl line 215, <GEN31> line 1.
Use of uninitialized value $target_id in regexp compilation at phyds.2.pl line 215, <GEN31> line 1.
Use of uninitialized value $target_id in regexp compilation at phyds.2.pl line 215, <GEN31> line 1.
Use of uninitialized value $target_id in regexp compilation at phyds.2.pl line 215, <GEN31> line 1.
Use of uninitialized value $target_id in regexp compilation at phyds.2.pl line 216, <GEN31> line 1.
Total paralogs found: 2
Trees with paralogs: 1
Trees with Split Paralogs:0

**OG0018625_gene_list.txt** looks like this:
`apple_prot_Mdg_15g019820 fruticosa_prot_Pfrut_045748-RA peach_prot_Prupe.7G202100.1 subA_proteins_Pcer_056916-RA subB_proteins_Pcer_054406-RA sweet_cherry_prot_FUN_039157-T`

and the tree it should be finding in the directory that has those genes in it (**OG0018625.raxml.bestTree**)
looks like this:
`((((subA_proteins_Pcer_056916-RA:0.007265,sweet_cherry_prot_FUN_039157-T1:0.000001):0.018259,(subB_proteins_Pcer_054406-RA:0.000001,fruticosa_prot_Pfrut_045748-RA:0.000001):0.000001):0.000001,peach_prot_Prupe.7G202100.1:0.010818):0.061429,apple_prot_Mdg_15g019820:0.061429);`
Any idea why I might be getting this error? Am I missing something critical here? (sorry in advance - I'm no perl expert but I know regular expressions well enough!)

Thanks for any and all advice you can offer - take care!
Charity

**Comment by goeckeritz** [comment]
(figured it out...) sorry to bother!

**Comment by mrmckain** [comment]
Glad you worked it out.  Please let me know if there are any improvements I can do to help.


Michael R. McKain, Ph.D.

Assistant Professor, Department of Biological Sciences

Curator, The University of Alabama Herbarium (UNA)

The University of Alabama<https://www.ua.edu/>
411 Mary Harmon Bryant Hall
Box 870344
Tuscaloosa, AL 35487
Phone 205-348-1826<tel:205-348-1826> | Mobile 706-248-1878<tel:706-248-1878>
***@***.******@***.***> | https://bsc.ua.edu/

[The University of Alabama]<https://www.ua.edu/>

[Twitter] <http://twitter.com/mrmckain>


________________________________
From: Charity Goeckeritz ***@***.***>
Sent: Friday, January 14, 2022 10:53 AM
To: mrmckain/PhyDS ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] Re: [mrmckain/PhyDS] Use of uninitialized value $target_id (Issue #2)


(figured it out...) sorry to bother!

—
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmrmckain%2FPhyDS%2Fissues%2F2%23issuecomment-1013291563&data=04%7C01%7Cmrmckain%40ua.edu%7C7215ccea5afd486c8ab208d9d77e6378%7C2a00728ef0d040b4a4e8ce433f3fbca7%7C0%7C0%7C637777760105216800%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=TFRJmf3bB5L4MBa4rhG8phkkL90OOUUjmteLIsXON8A%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAPIMUZUFMBY4CPPQXSOBODUWBIINANCNFSM5L4OGQKQ&data=04%7C01%7Cmrmckain%40ua.edu%7C7215ccea5afd486c8ab208d9d77e6378%7C2a00728ef0d040b4a4e8ce433f3fbca7%7C0%7C0%7C637777760105216800%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=994IgAuUtKQnVC6b5mJZ%2BbPzcH%2BZHU2LW8EkKgqZ6iE%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cmrmckain%40ua.edu%7C7215ccea5afd486c8ab208d9d77e6378%7C2a00728ef0d040b4a4e8ce433f3fbca7%7C0%7C0%7C637777760105373052%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=4IKBiOflJb14B9y8k6KYxWSQDe6lHarZ95f%2FpgxcsUE%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cmrmckain%40ua.edu%7C7215ccea5afd486c8ab208d9d77e6378%7C2a00728ef0d040b4a4e8ce433f3fbca7%7C0%7C0%7C637777760105373052%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=p89ySEA8FDkna1n46p0M6a2Jvmm1csVAlPo8H7DOlcg%3D&reserved=0>.
