### ISSUE TITLE
For orthogroups with many paralogs, phyDS only searches for the first two in the list

### ISSUE THREAD

**Issue by goeckeritz** [mrmckain/PhyDS#3]
Hi Michael, 

Sorry to bother you again! I seem to have it another issue... 

When I was using phyDS earlier this month, I was only searching for the sister hit of two 'species' (they're actually subgenomes) in 1:1 orthologous groups. Meaning, for every one of my paralogs list given to phyDS with -p, there were only 2 genes to search for. 

Now I'd like to search for the sister hit with orthologous groups that aren't necessarily 1:1. So, if I want to find the sister hits for two species, my paralogs list could have 2+ genes to search for in all of my trees. However, phyDS seems to only be searching the trees for the first two genes in my paralogs list. 

For example, for a given orthogroup, my list might look like:

`subA_proteins_Pcer_019737-RA    subA_proteins_Pcer_019742-RA    subA_proteins_Pcer_019740-RA    subA_proteins_Pcer_019745-RA    subA_proteins_Pcer_019748-RA    subA_proteins_Pcer_019762-RA    subA_proteins_Pcer_019763-RA    subA_proteins_Pcer_019767-RA    subA_proteins_Pcer_019768-RA    subA_proteins_Pcer_019765-RA    subA_proteins_Pcer_019764-RA    subA_proteins_Pcer_019772-RA    subA_proteins_Pcer_019771-RA    subA_proteins_Pcer_019769-RA    subA_proteins_Pcer_019773-RA    subA_proteins_Pcer_019776-RA    subA_proteins_Pcer_019774-RA    subA_proteins_Pcer_019778-RA    subA_proteins_Pcer_019780-RA    subA_proteins_Pcer_020007-RA    subB_proteins_Pcer_032019-RA    subB_proteins_Pcer_033321-RA    subB_proteins_Pcer_033317-RA    subB_proteins_Pcer_033336-RA    subB_proteins_Pcer_033338-RA    subB_proteins_Pcer_033341-RA    subB_proteins_Pcer_033337-RA    subB_proteins_Pcer_033340-RA    subB_proteins_Pcer_033335-RA    subB_proteins_Pcer_033343-RA    subB_proteins_Pcer_033342-RA    subB_proteins_Pcer_033344-RA    subB_proteins_Pcer_033351-RA    subB_proteins_Pcer_033350-RA    subB_proteins_Pcer_033360-RA    subB_proteins_Pcer_033358-RA    subB_proteins_Pcer_033347-RA    subB_proteins_Pcer_033349-RA`

My BSV cutoff is 80. What appears to be happening is that phyDS will search for subA_proteins_Pcer_019737-RA and subA_proteins_Pcer_019742-RA, and if both are sister to a taxon hit I am not ignoring, great! Both will be reported in the Subgenome_Results file. If only one of those two does, it only reports the one. Or if none - no files. Never more than the first two.

I know something is wrong because I've been looking at some of the trees as a sanity check to see if the amount of hits are correct based on my parameters. For example, subA_proteins_Pcer_019772-RA is sister to a taxon of interest with a BSV of 82 but this doesn't make its way into any of the results files. 

Do you know why phyDS is behaving this way? I was hoping I would be able to use it to search for the sister taxon hit of many paralogs in an orthogroup but perhaps I am confused about its abilities? 

Any thoughts, advice, etc, you could offer are much appreciated! And please do let me know if I was confusing or unclear somewhere. 

Thank you!
Kindly, 
Charity

**Comment by mrmckain** [comment]
Hi Charity,

PhyDS doesn't handle the paralogs file like that. You would need to make a two column list with repeated genes. In this, 

subA_proteins_Pcer_019737-RA subA_proteins_Pcer_019742-RA subA_proteins_Pcer_019740-RA

becomes

subA_proteins_Pcer_019737-RA subA_proteins_Pcer_019742-RA 
subA_proteins_Pcer_019737-RA subA_proteins_Pcer_019740-RA

If you want to all possible combos, then:

subA_proteins_Pcer_019737-RA subA_proteins_Pcer_019742-RA 
subA_proteins_Pcer_019737-RA subA_proteins_Pcer_019740-RA
subA_proteins_Pcer_019742-RA subA_proteins_Pcer_019740-RA

Hope this helps.

Best,
Michael

**Comment by goeckeritz** [comment]
Hi Michael, 

Thanks for getting back to me, and letting me know that PhyDS works differently than I originally thought... I definitely want to search for every possible paralog independently in all of orthogroups... 

should I try to code a list of objects (genes or paralogs) into every possible combination of paralogs? Maybe I can fiddle in R or bash to try to do this. 

I'm a little confused though -- why exactly do they have to be in 'pairs' and repeated? If I give it all possible combos, it will then search for every gene and report its sister in the tree (if it passes the BSV filter), correct?

Thanks so much for your help!
Kindly, 
Charity

**Comment by mrmckain** [comment]
Hi Charity,

Genes are given in pairs because they are assumed to be paralogs. The script is set up to need this information from the user. The code is written to expect two columns, which is why they are to be in pairs. The code will not double count any groups, but the pairs should only provide the same two genes together once. There is a script in bin that will make you a list from your trees of all possible combinations. You can then let the pattern emerge instead of having to provide putative paralogs. 

To run it: perl estimate_paralogs_from_trees.pl --trees directory_of_trees --outgroups list --name ID_for_run
These are the same parameters as you use for the main script.

Let me know if you have more questions,
Michael

**Comment by goeckeritz** [comment]
Ahh I see. Thanks Michael. I ended up putting my genes in a 2 column list more or less randomly for each orthogroup. As long as it checks every gene and reports its sister given the BSV value is sufficient, that's all I need! Which, upon manually checking the trees - was the case. 

Thanks again!!
Charity
